// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"condog/internal/config"
	"context"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, cfg config.AppConfig) (App, error) {
	diApp := ProvideApp(ctx, cfg)
	return diApp, nil
}
